---

- name: install apache2 and deps
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - php5 
   - php5-gd
   - php5-redis 
   - php5-mysql 
   - git 
   - unzip 
   - php5-curl
   - php5-mcrypt
   - php5-json
   - libapache2-mod-php5
  notify:
   - Restart Apache


- name: start apache2
  service: name=apache2 state=started